name: appwrite_dart_function
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  appwrite_function_types:
    path: ../appwrite_function_types

dev_dependencies:
  pedantic: ^1.10.0
